# This action run e2e test for pull requests
name: test
on: [pull_request]
jobs:
  e2e-mysql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    env:
      DB_DATABASE: lake_db
      DB_USER: root
      DB_PASSWORD: root
      DB_TYPE: mysql
      DB_URL: mysql://root:root@localhost:3306/lake_db
      REDIS_URL: redis://localhost:6379/1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: 'npm install'
      - name: setup mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - run: 'npm run test:e2e'
  # e2e-postgres:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x, 14.x, 15.x]
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #   env:
  #     DB_TYPE: postgres
  #     DB_URL: postgresql://postgres:postgres@localhost:5432/postgres
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: 'npm install'
  #     - run: 'npm run test:e2e'
